workflows:
  ios-workflow:
    name: iOS Workflow
    instance_type: mac_mini_m1
    max_build_duration: 120
    # integrations:
    #   app_store_connect: codemagic
    environment:
      groups:
        - manual_code_signing_ios_debug
      ios_signing:
        distribution_type: ad_hoc
        bundle_identifier: org.micromentor.mmFlutterApp
      vars:
        APP_ID: 6463767947 # <-- Put your APP ID here
      flutter: 3.16.5
      xcode: 15.2 # <-- set to specific version e.g. 14.3, 15.0 to avoid unexpected updates.
      cocoapods: 1.14.3
    scripts:
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Install pods
        script: |
          find . -name "Podfile" -execdir pod install \;
      - name: Flutter analyze
        script: |
          flutter analyze
      - name: Flutter unit tests
        script: |
          flutter test
        ignore_failure: true
      - name: Flutter build ipa and automatic versioning
        # (temp) set build number to 9, the latest in the MM app store is 8
        # TODO: set up automatic versioning, or use env vars for manual versioning
        script: |
          flutter build ipa --debug \
            --build-name=1.0.0 \
            --build-number=9 \
            --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
    publishing:
      # See the following link for details about email publishing - https://docs.codemagic.io/publishing-yaml/distribution/#email
      email:
        recipients:
          - chris_anderson@micromentor.org
        notify:
          success: true # To receive a notification when a build succeeds
          failure: true # To not receive a notification when a build fails
      # app_store_connect:
      #   auth: integration

      #   # Configuration related to TestFlight (optional)
      #   # Note: This action is performed during post-processing.
      #   submit_to_testflight: true
      #   beta_groups: # Specify the names of beta tester groups that will get access to the build once it has passed beta review.
      #     - group name 1
      #     - group name 2

      #   # Configuration related to App Store (optional)
      #   # Note: This action is performed during post-processing.
      #   submit_to_app_store: false